-- AlterTable
ALTER TABLE "public"."Bird" ALTER COLUMN "band" DROP NOT NULL,
ALTER COLUMN "band_1" DROP NOT NULL,
ALTER COLUMN "band_2" DROP NOT NULL,
ALTER COLUMN "band_3" DROP NOT NULL,
ALTER COLUMN "band_4" DROP NOT NULL;
