-- AddForeignKey
ALTER TABLE "AvgWinnerPrizes" ADD CONSTRAINT "AvgWinnerPrizes_ID_EVENT_fkey" FOREIGN KEY ("ID_EVENT") REFERENCES "Events"("ID_EVENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Basket" ADD CONSTRAINT "Basket_ID_RACE_fkey" FOREIGN KEY ("ID_RACE") REFERENCES "Race"("ID_RACE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Birds" ADD CONSTRAINT "Birds_LOST_ID_RACE_fkey" FOREIGN KEY ("LOST_ID_RACE") REFERENCES "Race"("ID_RACE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Birds" ADD CONSTRAINT "Birds_ID_PICTURE_fkey" FOREIGN KEY ("ID_PICTURE") REFERENCES "Picture"("ID_PICTURE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BirdsView" ADD CONSTRAINT "BirdsView_LOST_ID_RACE_fkey" FOREIGN KEY ("LOST_ID_RACE") REFERENCES "Race"("ID_RACE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BirdsView" ADD CONSTRAINT "BirdsView_ID_PICTURE_fkey" FOREIGN KEY ("ID_PICTURE") REFERENCES "Picture"("ID_PICTURE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Breeders" ADD CONSTRAINT "Breeders_ID_PICTURE_fkey" FOREIGN KEY ("ID_PICTURE") REFERENCES "Picture"("ID_PICTURE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_ID_FEE_SCHEME_fkey" FOREIGN KEY ("ID_FEE_SCHEME") REFERENCES "FeeScheme"("ID_FEE_SCHEME") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_ID_FINAL_PRIZE_SCHEME_fkey" FOREIGN KEY ("ID_FINAL_PRIZE_SCHEME") REFERENCES "PrizeScheme"("ID_PRIZE_SCHEME") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_ID_HOT_SPOT1_PRIZE_SCHEME_fkey" FOREIGN KEY ("ID_HOT_SPOT1_PRIZE_SCHEME") REFERENCES "PrizeScheme"("ID_PRIZE_SCHEME") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_ID_HOT_SPOT2_PRIZE_SCHEME_fkey" FOREIGN KEY ("ID_HOT_SPOT2_PRIZE_SCHEME") REFERENCES "PrizeScheme"("ID_PRIZE_SCHEME") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_ID_HOT_SPOT3_PRIZE_SCHEME_fkey" FOREIGN KEY ("ID_HOT_SPOT3_PRIZE_SCHEME") REFERENCES "PrizeScheme"("ID_PRIZE_SCHEME") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_ID_HOT_SPOT_AVG_PRIZE_SCHEME_fkey" FOREIGN KEY ("ID_HOT_SPOT_AVG_PRIZE_SCHEME") REFERENCES "PrizeScheme"("ID_PRIZE_SCHEME") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_ID_BETTING_SCHEME_fkey" FOREIGN KEY ("ID_BETTING_SCHEME") REFERENCES "BettingScheme"("ID_BETTING_SCHEME") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EventInventory" ADD CONSTRAINT "EventInventory_ID_EVENT_fkey" FOREIGN KEY ("ID_EVENT") REFERENCES "Events"("ID_EVENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EventInventory" ADD CONSTRAINT "EventInventory_ID_BREEDER_fkey" FOREIGN KEY ("ID_BREEDER") REFERENCES "Breeders"("ID_BREEDER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EventInventoryItem" ADD CONSTRAINT "EventInventoryItem_ID_EVENT_INVENTORY_fkey" FOREIGN KEY ("ID_EVENT_INVENTORY") REFERENCES "EventInventory"("ID_EVENT_INVENTORY") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EventInventoryItem" ADD CONSTRAINT "EventInventoryItem_ID_BIRD_fkey" FOREIGN KEY ("ID_BIRD") REFERENCES "Birds"("ID_BIRD") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EventInventoryItem" ADD CONSTRAINT "EventInventoryItem_ID_REPLACED_ITEM_fkey" FOREIGN KEY ("ID_REPLACED_ITEM") REFERENCES "EventInventoryItem"("ID_EVENT_INVENTORY_ITEM") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EventRaceNumber" ADD CONSTRAINT "EventRaceNumber_ID_NUMBER_GROUP_fkey" FOREIGN KEY ("ID_NUMBER_GROUP") REFERENCES "RaceNumberGroup"("ID_RACE_NUMBER_GROUP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EventRaceNumber" ADD CONSTRAINT "EventRaceNumber_ID_EVENT_fkey" FOREIGN KEY ("ID_EVENT") REFERENCES "Events"("ID_EVENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Log" ADD CONSTRAINT "Log_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "Users"("ID_USER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LogUserLoggedin" ADD CONSTRAINT "LogUserLoggedin_ID_LOG_fkey" FOREIGN KEY ("ID_LOG") REFERENCES "Log"("ID_LOG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LogUserLoggedin" ADD CONSTRAINT "LogUserLoggedin_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "Users"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LogUserLoggedout" ADD CONSTRAINT "LogUserLoggedout_ID_LOG_fkey" FOREIGN KEY ("ID_LOG") REFERENCES "Log"("ID_LOG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LostHistory" ADD CONSTRAINT "LostHistory_ID_BIRD_fkey" FOREIGN KEY ("ID_BIRD") REFERENCES "Birds"("ID_BIRD") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LostHistory" ADD CONSTRAINT "LostHistory_ID_RACE_fkey" FOREIGN KEY ("ID_RACE") REFERENCES "Race"("ID_RACE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Partners" ADD CONSTRAINT "Partners_ID_EVENT_INVENTORY_fkey" FOREIGN KEY ("ID_EVENT_INVENTORY") REFERENCES "EventInventory"("ID_EVENT_INVENTORY") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Partners" ADD CONSTRAINT "Partners_ID_BREEDER_fkey" FOREIGN KEY ("ID_BREEDER") REFERENCES "Breeders"("ID_BREEDER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payments" ADD CONSTRAINT "Payments_ID_EVENT_INVENTORY_fkey" FOREIGN KEY ("ID_EVENT_INVENTORY") REFERENCES "EventInventory"("ID_EVENT_INVENTORY") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payments" ADD CONSTRAINT "Payments_ID_PICTURE_fkey" FOREIGN KEY ("ID_PICTURE") REFERENCES "Picture"("ID_PICTURE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PerchFeeItem" ADD CONSTRAINT "PerchFeeItem_ID_FEE_SCHEME_fkey" FOREIGN KEY ("ID_FEE_SCHEME") REFERENCES "FeeScheme"("ID_FEE_SCHEME") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PrizeSchemeItem" ADD CONSTRAINT "PrizeSchemeItem_ID_PRIZE_SCHEME_fkey" FOREIGN KEY ("ID_PRIZE_SCHEME") REFERENCES "PrizeScheme"("ID_PRIZE_SCHEME") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PrizeValue" ADD CONSTRAINT "PrizeValue_ID_EVENT_fkey" FOREIGN KEY ("ID_EVENT") REFERENCES "Events"("ID_EVENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PrizeValue" ADD CONSTRAINT "PrizeValue_ID_RACE_TYPE_fkey" FOREIGN KEY ("ID_RACE_TYPE") REFERENCES "RaceType"("ID_RACE_TYPE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PrizeValue" ADD CONSTRAINT "PrizeValue_ID_PRIZE_SCHEME_ITEM_fkey" FOREIGN KEY ("ID_PRIZE_SCHEME_ITEM") REFERENCES "PrizeSchemeItem"("ID_PRIZE_SCHEME_ITEM") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Race" ADD CONSTRAINT "Race_ID_RACE_TYPE_fkey" FOREIGN KEY ("ID_RACE_TYPE") REFERENCES "RaceType"("ID_RACE_TYPE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Race" ADD CONSTRAINT "Race_ID_EVENT_fkey" FOREIGN KEY ("ID_EVENT") REFERENCES "Events"("ID_EVENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RaceIgnoreBird" ADD CONSTRAINT "RaceIgnoreBird_ID_RACE_fkey" FOREIGN KEY ("ID_RACE") REFERENCES "Race"("ID_RACE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RaceIgnoreBird" ADD CONSTRAINT "RaceIgnoreBird_ID_EVENT_INVENTORY_ITEM_fkey" FOREIGN KEY ("ID_EVENT_INVENTORY_ITEM") REFERENCES "EventInventoryItem"("ID_EVENT_INVENTORY_ITEM") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RaceItem" ADD CONSTRAINT "RaceItem_ID_RACE_fkey" FOREIGN KEY ("ID_RACE") REFERENCES "Race"("ID_RACE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RaceItem" ADD CONSTRAINT "RaceItem_ID_INVENTORY_ITEM_fkey" FOREIGN KEY ("ID_INVENTORY_ITEM") REFERENCES "EventInventoryItem"("ID_EVENT_INVENTORY_ITEM") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RaceItemResult" ADD CONSTRAINT "RaceItemResult_ID_RACE_ITEM_fkey" FOREIGN KEY ("ID_RACE_ITEM") REFERENCES "RaceItem"("ID_RACE_ITEM") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RaceItemScan" ADD CONSTRAINT "RaceItemScan_ID_RACE_fkey" FOREIGN KEY ("ID_RACE") REFERENCES "Race"("ID_RACE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RaceItemScan" ADD CONSTRAINT "RaceItemScan_ID_RACE_ITEM_fkey" FOREIGN KEY ("ID_RACE_ITEM") REFERENCES "RaceItem"("ID_RACE_ITEM") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RacePhantomBird" ADD CONSTRAINT "RacePhantomBird_ID_RACE_fkey" FOREIGN KEY ("ID_RACE") REFERENCES "Race"("ID_RACE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RacePhantomBird" ADD CONSTRAINT "RacePhantomBird_ID_BIRD_fkey" FOREIGN KEY ("ID_BIRD") REFERENCES "Birds"("ID_BIRD") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RacePhantomBird" ADD CONSTRAINT "RacePhantomBird_ID_EVENT_fkey" FOREIGN KEY ("ID_EVENT") REFERENCES "Events"("ID_EVENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RaceType" ADD CONSTRAINT "RaceType_ID_NUMBER_GROUP_fkey" FOREIGN KEY ("ID_NUMBER_GROUP") REFERENCES "RaceNumberGroup"("ID_RACE_NUMBER_GROUP") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RightGroupLines" ADD CONSTRAINT "RightGroupLines_ID_RIGHT_GROUP_fkey" FOREIGN KEY ("ID_RIGHT_GROUP") REFERENCES "RightGroups"("ID_RIGHT_GROUP") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StandardShowPercentage" ADD CONSTRAINT "StandardShowPercentage_ID_BETTING_SCHEME_fkey" FOREIGN KEY ("ID_BETTING_SCHEME") REFERENCES "BettingScheme"("ID_BETTING_SCHEME") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SystemRequirements" ADD CONSTRAINT "SystemRequirements_ID_SYSTEM_UPDATE_fkey" FOREIGN KEY ("ID_SYSTEM_UPDATE") REFERENCES "SystemUpdates"("ID_SYSTEM_UPDATE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TmpBets" ADD CONSTRAINT "TmpBets_ID_EVENT_INVENTORY_ITEM_fkey" FOREIGN KEY ("ID_EVENT_INVENTORY_ITEM") REFERENCES "EventInventoryItem"("ID_EVENT_INVENTORY_ITEM") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserRightGroups" ADD CONSTRAINT "UserRightGroups_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "Users"("ID_USER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserRightGroups" ADD CONSTRAINT "UserRightGroups_ID_RIGHT_GROUP_fkey" FOREIGN KEY ("ID_RIGHT_GROUP") REFERENCES "RightGroups"("ID_RIGHT_GROUP") ON DELETE SET NULL ON UPDATE CASCADE;
