-- CreateTable
CREATE TABLE "Team" (
    "ID_TEAM" SERIAL NOT NULL,
    "TEAM_NAME" TEXT,
    "ID_BREEDER" INTEGER,

    CONSTRAINT "Team_pkey" PRIMARY KEY ("ID_TEAM")
);

-- CreateIndex
CREATE UNIQUE INDEX "Team_TEAM_NAME_ID_BREEDER_key" ON "Team"("TEAM_NAME", "ID_BREEDER");

-- AddForeignKey
ALTER TABLE "Team" ADD CONSTRAINT "Team_ID_BREEDER_fkey" FOREIGN KEY ("ID_BREEDER") REFERENCES "Breeders"("ID_BREEDER") ON DELETE SET NULL ON UPDATE CASCADE;
