-- AlterTable
ALTER TABLE "EventInventoryItem" ALTER COLUMN "BETS_REFUND" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ENTRY_FEE_VALUE" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ENTRY_REFUND" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "HOT_SPOT_FEE_VALUE" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "HOT_SPOT_REFUND" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "PERCH_FEE_VALUE" SET DATA TYPE DOUBLE PRECISION;
