-- AlterTable
ALTER TABLE "Payments" ADD COLUMN     "ID_BREEDER" INTEGER;

-- AddForeignKey
ALTER TABLE "Payments" ADD CONSTRAINT "Payments_ID_BREEDER_fkey" FOREIGN KEY ("ID_BREEDER") REFERENCES "Breeders"("ID_BREEDER") ON DELETE SET NULL ON UPDATE CASCADE;
