-- AddForeignKey
ALTER TABLE "RaceItem" ADD CONSTRAINT "RaceItem_ID_DIST_BASKET_fkey" FOREIGN KEY ("ID_DIST_BASKET") REFERENCES "Basket"("ID_BASKET") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RaceItem" ADD CONSTRAINT "RaceItem_ID_RACE_BASKET_fkey" FOREIGN KEY ("ID_RACE_BASKET") REFERENCES "Basket"("ID_BASKET") ON DELETE SET NULL ON UPDATE CASCADE;
