-- DropForeignKey
ALTER TABLE "RfidScans" DROP CONSTRAINT "RfidScans_ID_BIRD_fkey";

-- DropForeignKey
ALTER TABLE "RfidScans" DROP CONSTRAINT "RfidScans_ID_RACE_fkey";

-- DropIndex
DROP INDEX "RfidScans_ID_BIRD_idx";

-- DropIndex
DROP INDEX "RfidScans_ID_RACE_idx";

-- AlterTable
ALTER TABLE "RfidScans" ALTER COLUMN "RFID_TAG" SET DATA TYPE TEXT,
ALTER COLUMN "SCANNER_ID" SET DATA TYPE TEXT,
ALTER COLUMN "TIMESTAMP" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "CREATED_AT" SET DATA TYPE TIMESTAMP(3);

-- AddForeignKey
ALTER TABLE "RfidScans" ADD CONSTRAINT "RfidScans_ID_BIRD_fkey" FOREIGN KEY ("ID_BIRD") REFERENCES "Birds"("ID_BIRD") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RfidScans" ADD CONSTRAINT "RfidScans_ID_RACE_fkey" FOREIGN KEY ("ID_RACE") REFERENCES "Race"("ID_RACE") ON DELETE SET NULL ON UPDATE CASCADE;
