-- Create RFID Scans table
CREATE TABLE IF NOT EXISTS "RfidScans" (
    "ID_RFID_SCAN" SERIAL PRIMARY KEY,
    "RFID_TAG" VARCHAR(255) NOT NULL,
    "SCANNER_ID" VARCHAR(255) NOT NULL,
    "TIMESTAMP" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PROCESSED" BOOLEAN NOT NULL DEFAULT false,
    "ID_BIRD" INTEGER REFERENCES "Birds"("ID_BIRD") ON DELETE SET NULL,
    "ID_RACE" INTEGER REFERENCES "Race"("ID_RACE") ON DELETE SET NULL,
    "NOTES" TEXT,
    "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS "RfidScans_RFID_TAG_idx" ON "RfidScans"("RFID_TAG");
CREATE INDEX IF NOT EXISTS "RfidScans_SCANNER_ID_idx" ON "RfidScans"("SCANNER_ID");
CREATE INDEX IF NOT EXISTS "RfidScans_TIMESTAMP_idx" ON "RfidScans"("TIMESTAMP");
CREATE INDEX IF NOT EXISTS "RfidScans_PROCESSED_idx" ON "RfidScans"("PROCESSED");
CREATE INDEX IF NOT EXISTS "RfidScans_ID_BIRD_idx" ON "RfidScans"("ID_BIRD");
CREATE INDEX IF NOT EXISTS "RfidScans_ID_RACE_idx" ON "RfidScans"("ID_RACE");

-- Add comment to table
COMMENT ON TABLE "RfidScans" IS 'RFID scanner tag readings for bird tracking';
