-- AlterTable
ALTER TABLE "BettingScheme" ADD COLUMN     "CREATOR_ID" INTEGER;

-- AlterTable
ALTER TABLE "FeeScheme" ADD COLUMN     "CREATOR_ID" INTEGER;

-- AlterTable
ALTER TABLE "PrizeScheme" ADD COLUMN     "CREATOR_ID" INTEGER;

-- AddForeignKey
ALTER TABLE "BettingScheme" ADD CONSTRAINT "BettingScheme_CREATOR_ID_fkey" FOREIGN KEY ("CREATOR_ID") REFERENCES "OrganizerData"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FeeScheme" ADD CONSTRAINT "FeeScheme_CREATOR_ID_fkey" FOREIGN KEY ("CREATOR_ID") REFERENCES "OrganizerData"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PrizeScheme" ADD CONSTRAINT "PrizeScheme_CREATOR_ID_fkey" FOREIGN KEY ("CREATOR_ID") REFERENCES "OrganizerData"("ID") ON DELETE SET NULL ON UPDATE CASCADE;
